apiVersion: batch/v1
kind: Job
metadata:
  name: generate
  annotations:
    kueue.x-k8s.io/queue-name: user-queue
spec:
  ttlSecondsAfterFinished: 100
  completions: 10
  parallelism: 10
  completionMode: Indexed
  template:
    spec:
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
      volumes:
        - name: google-cloud-key
          secret:
            secretName: gcs-key
      containers:
      - name: generate
        image: us-docker.pkg.dev/trillionsort/images/generate:3e8ff1ae13a02b06fe2866154b9eb97dbfbde70c
        command: ["/generate"]
        args: ["-count", "1_000_000", "-file", "generate.txt", "-fileindex", "$(JOB_COMPLETION_INDEX)", "-objectstorage", "-bucket", "demo-00-mofi"]
        volumeMounts:
          - name: google-cloud-key
            mountPath: "/var/secrets/google"
        env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: "/var/secrets/google/key.json"
        resources:
          requests:
            memory: "1Gi"
            cpu: "1"
          limits:
            memory: "1Gi"
            cpu: "1"
      restartPolicy: Never
