apiVersion: batch/v1
kind: Job
metadata:
  name: sort
spec:
  ttlSecondsAfterFinished: 100
  completions: 10
  parallelism: 10
  completionMode: Indexed
  template:
    spec:
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
      volumes:
        - name: filestore
          persistentVolumeClaim:
            claimName: podpvc
            readOnly: false
      containers:
      - name: sort
        image: us-docker.pkg.dev/trillionsort/images/sortfile:2ba77694b82b0a8b4530314b0f6b7e269c9f3cc4
        command: ["/sortfile"]
        args: ["-input", "data/split.txt", "-index", "$(JOB_COMPLETION_INDEX)", "-output", "data/sort.txt"]
        volumeMounts:
          - name: filestore
            mountPath: "/data"
        resources:
          requests:
            memory: "2Gi"
            cpu: "4"
          limits:
            memory: "2Gi"
            cpu: "4"
      restartPolicy: Never
