apiVersion: batch/v1
kind: Job
metadata:
  name: join
  annotations:
    kueue.x-k8s.io/queue-name: user-queue
spec:
  ttlSecondsAfterFinished: 100
  completions: 1
  template:
    spec:
      securityContext:
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
      volumes:
        - name: filestore
          persistentVolumeClaim:
            claimName: podpvc
            readOnly: false
      containers:
      - name: join
        image: us-docker.pkg.dev/trillionsort/images/joinfile:6327330fbfdb0baceee563ac36dafc0d5e7554b0
        command: ["/joinfile"]
        args: ["-dir", "data", "-pattern", "generate", "-output", "data/join.txt"]
        volumeMounts:
          - name: filestore
            mountPath: "/data"
        resources:
          requests:
            memory: "20Gi"
            cpu: "10"
          limits:
            memory: "20Gi"
            cpu: "10"
      restartPolicy: Never
