apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-patcher
  namespace: default
  labels:
    app: argo-workflows
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-patcher-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: pod-patcher
subjects:
- kind: ServiceAccount
  name: default
  namespace: default
